# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AlipayHeader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AlipayHeader
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'Masonry', '~> 1.1.0'

end
